# WIP: TechBridge Capstone Project: Smile Mart Assistant Chatbot with Azure Spring App

Status: Work in Progress

This repository is developing a temporary token provider for the Azure-powered chatbot application, designed to facilitate secure and efficient customer service operations for Smile Mart.

## Table of Contents
- [Executive Summary](#executive-summary)
- [Team & Responsibilities](#team--responsibilities)
- [Technical Approach](#technical-approach)
- [Business Case](#business-case)
- [Development and Deployment Guide](#development-and-deployment-guide)
- [Azure README Integration](#azure-readme-integration)
- [Further Reading & Resources](#further-reading--resources)
- [Acknowledgments](#acknowledgments)


## Executive Summary
The Smile Mart Assistant Chatbot project encapsulates the integration of Azure Cognitive Services and Azure Spring Apps to enhance customer interaction within the Smile Mart retail environment. This solution aims to streamline customer service operations, reduce wait times, and provide 24/7 assistance, leading to an overall improved customer experience and satisfaction.

## Team & Responsibilities

### Team:
- Melissa Vargas
- Mary Nichols
- Gaetano Barreca
- Kendall Drummond
- Kayla Thorne
- Yvonne Sudlow

## Technical Approach
Our project harnesses the capabilities of Azure Cognitive Services, specifically QnA Maker, for its natural language processing prowess, paired with Azure Spring Apps for a robust backend. The integration with GitHub Actions facilitates continuous integration and deployment, ensuring smooth and consistent updates.

### Chatbot Solution:
- QnA Maker to understand and respond to customer queries
- Azure Spring Apps for scalable backend services
- GitHub Actions for streamlined deployment workflows

### Backend Development:
- Java for robust and efficient backend logic
- Azure Spring Apps (ASA) leveraged for secure token generation and management
- Hosted on GitHub Pages for easy access and visibility

### Technical Limitations and Future Upgrades:
- Limited to current Azure tier features with plans to evaluate the upgrade to Azure Enterprise for expanded capabilities
- Development of a roadmap for incorporating additional Azure services and creating a more personalized user experience

## Business Case
The Assistant Chatbot acts as a virtual customer service representative, capable of handling a wide array of customer inquiries without human intervention, allowing Smile Mart to allocate human resources more effectively and improving operational efficiency.

## Development and Deployment Guide
A step-by-step guide for development and deployment.


## Development and Deployment Guide

### Session 1: Initial Findings and Direction
The project kickoff phase encompassed identifying the core customer service challenges and establishing objectives for the chatbot to address.

### Session 2: In-Depth Development
Development focused on creating a responsive and accurate chatbot, iterating through various designs, and ensuring seamless integration with existing Smile Mart systems.

#### Repositories in Progress:
- [Smile Mart Store Landing Page with Chatbot Logic](https://github.com/gaebar/SmileMart-Store-Landing-Page)
- [Smile Mart AssistantBot AzureSpringApp](https://github.com/gaebar/SmileMart-AssistantBot-AzureSpringApp)

### Smile Mart Website Link
[Smile Mart Testing Website](https://gaebar.github.io/SmileMart-Store-Landing-Page/src/)

### Steps:
The setup process involves configuring the QnA chatbot within the Azure portal, deploying the backend through Azure Spring Apps, and integrating the frontend with the chatbot service.

#### STEP 1: Create and Configure Custom QnA Chatbot

- Chosen for its adaptive learning capabilities and seamless user experience
- Follow the provided [Azure Chatbot Tutorial](https://docs.microsoft.com/azure/cognitive-services/qnamaker/tutorials/create-publish-query-in-portal)

#### STEP 2 and STEP 3: Deployment and Integration

- Deploy backend services using Azure Spring Apps for efficient scaling and management
- Implement GitHub Actions for a CI/CD pipeline, automating the deployment process

## Azure README Integration
After careful consideration, the Azure Spring App README will be adapted and integrated to provide clear and specific instructions related to the deployment and management of the Azure resources utilized in our project.

## Further Reading & Resources
Explore these additional resources to understand the technical details and broader context of our project:

- [Azure Cognitive Services Documentation](https://docs.microsoft.com/azure/cognitive-services/)
- [Azure Spring Apps Documentation](https://docs.microsoft.com/azure/spring-apps/)

## Acknowledgments
Special thanks to the TechBridge team, Smile Mart's IT department, and all the stakeholders who have provided invaluable feedback and support throughout the lifecycle of this project.


































___________________________________________________________________________

:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-boot-for-azure

Before delving into the step-by-step execution of the application, you can simply click the Deploy to Azure button. This will instantly deploy the app to Azure Spring Apps.

|===
|Deploy to Azure Spring Apps |
|Consumption plan
|image:https://aka.ms/deploytoazurebutton[link=https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fspring-guides%2Fgs-spring-boot-for-azure%2Fmain%2Finfra%2Fazuredeploy-asa-consumption.json]

|Basic/Standard plan
|image:https://aka.ms/deploytoazurebutton[link=https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fspring-guides%2Fgs-spring-boot-for-azure%2Fmain%2Finfra%2Fazuredeploy-asa-standard.json]

|Enterprise plan
|image:https://aka.ms/deploytoazurebutton[link=https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fspring-guides%2Fgs-spring-boot-for-azure%2Fmain%2Finfra%2Fazuredeploy-asa-enterprise.json]
|===

This article walks you through deploying a Spring Boot application to https://learn.microsoft.com/azure/spring-apps/overview[Azure Spring Apps].

IMPORTANT: You are recommended to check out https://learn.microsoft.com/azure/spring-apps/quickstart[Azure Spring Apps quick start doc] for the latest instructions for the same task.

== What you'll build

You'll clone a sample Spring Boot application from GitHub and then use Maven to deploy it to Azure Spring Apps.

== What you'll need

The following prerequisites are required in order to follow the steps in this article:

* An Azure subscription. If you don't have an Azure subscription, you can sign up for a https://azure.microsoft.com/pricing/free-trial/[free Azure account] or activate your https://azure.microsoft.com/pricing/member-offers/msdn-benefits-details/[MSDN subscriber benefits].
* An http://www.oracle.com/technetwork/java/javase/downloads/[Java Development Kit (JDK)], version 17 or later.
* A https://github.com/[Git] client.

== Build and run the web app locally

In this section, you will clone a Spring Boot application and test it locally.

. Open a terminal window.
. Create a local directory to hold your Spring Boot application by typing `mkdir SpringBoot`
. Change to that directory by typing `cd SpringBoot`.
. Clone the https://github.com/spring-guides/gs-spring-boot-for-azure[Deploying a Spring Boot app to Azure] sample project into the directory you created by typing `git clone https://github.com/spring-guides/gs-spring-boot-for-azure`
. Change to the directory of the completed project by typing `cd gs-spring-boot-for-azure/complete`
. Build the JAR file using Maven by typing `./mvnw clean package`
. When the web app has been created, start it by typing `./mvnw spring-boot:run`
. Test it locally by either visiting http://localhost:8080 or typing `curl http://localhost:8080` from another terminal window.
. You should see the following message displayed: *Hello World*.

== Config and deploy the app to Azure Spring Apps

=== Provision an Azure Spring Apps instance

. In a web browser, open the https://portal.azure.com/[Azure portal], and sign in to your account.
. Search for `Azure Spring Apps` and then select `Azure Spring Apps`.
. On the overview page, select Create, and then do the following:
  a. In the Service Name box, specify the name of your service instance. The name must be from 4 to 32 characters long and can contain only lowercase letters, numbers, and hyphens. The first character of the service name must be a letter, and the last character must be either a letter or a number.
  b. In the Subscription drop-down list, select the subscription you want to be billed for this resource.
  c. In the Resource group box, create a new resource group. Creating resource groups for new resources is a best practice.
  d. In the Location drop-down list, select the location for your service instance.
. It takes about 5 minutes for the service to be deployed.

=== Add configuration for deployment

. Config the web app with https://github.com/microsoft/azure-maven-plugins/tree/develop/azure-spring-apps-maven-plugin[Maven Plugin for Azure Spring Apps] by this command:
+
----
export MAVEN_OPTS="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED"
./mvnw com.microsoft.azure:azure-spring-apps-maven-plugin:1.18.0:config -DadvancedOptions
----
+
 - Command explanation:
   * `export MAVEN_OPTS="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED"` is used to avoid the problem tracked in https://github.com/microsoft/azure-maven-plugins/issues/2222[azure-maven-plugins#2222].
   * This maven goal will first authenticate with Azure, if you have logged in with https://docs.microsoft.com/en-us/cli/azure/[Azure CLI], it will consume its existing authentication token. Otherwise, it will get you logged in with https://github.com/microsoft/azure-maven-plugins/wiki/Azure-Maven-Plugin/[azure-maven-plugin] automatically.

 - Input necessary information:
   * Select subscription: Select the subscription which host the Azure Spring Apps you just created.
   * Select Azure Spring Apps for deployment: Select the Azure Spring Apps you just created.
   * Input runtime Java version(Java 11): Java 17
   * Expose public access for this app boot-for-azure? (y/N): y
   * For other options, just select the default value.
 - Here is a sample terminal output:
+
----
~@Azure:~/gs-spring-boot/complete$ ./mvnw com.microsoft.azure:azure-spring-apps-maven-plugin:1.14.0:config -DadvancedOptions
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building boot-for-azure 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- azure-spring-apps-maven-plugin:1.14.0:config (default-cli) @ demo ---
...
Available subscription:
 1. xxx
...
Select subscription [1-105] (20):
...
Available Azure Spring Apps:
 1. xxx
...
Select Azure Spring Apps for deployment: [1-28] (1): 1
[INFO] Using Azure Spring Apps: xxx
Input the app name (demo):
Expose public access for this app boot-for-azure? (y/N):y
Summary of properties:
Subscription id   : xxx
Resource group name : xxx
Azure Spring Apps name : xxx
App name          : demo
Public access     : yes
Instance count    : 1
CPU count         : 1
Memory size(GB)   : 1
Runtime Java version : Java 17
Confirm to save all the above configurations (Y/n):Y
----
+
. Optionally, open the *pom.xml* to see the new added content.
+
----
<plugin>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-spring-apps-maven-plugin</artifactId>
    <version>1.14.0</version>
    <configuration>
        <subscriptionId>xxx</subscriptionId>
        <resourceGroup>xxx</resourceGroup>
        <clusterName>xxx</clusterName>
        <appName>demo</appName>
        <isPublic>true</isPublic>
        <deployment>
            <cpu>1</cpu>
            <memoryInGB>1</memoryInGB>
            <instanceCount>1</instanceCount>
            <runtimeVersion>Java 17</runtimeVersion>
            <resources>
                <resource>
                    <filtering/>
                    <mergeId/>
                    <targetPath/>
                    <directory>${project.basedir}/target</directory>
                    <includes>
                        <include>*.jar</include>
                    </includes>
                </resource>
            </resources>
        </deployment>
    </configuration>
</plugin>
----

=== Deploy the app

. Run this command to deploy the app:
+
----
./mvnw azure-spring-apps:deploy
----
+
. It might take a few minutes to deploy. After deploy finished, there will be a URL shown in the output. Navigate to the URL in a web browser. You should see the message displayed: `Hello World`.

== Summary

Congratulations! You built and deployed a Spring Boot app to Azure Spring Apps. You can visit the https://portal.azure.com/[Azure portal] to manage it.

IMPORTANT: Don't forget to delete the Azure resources created if no longer needed. 

== Run with AZD
You can also use https://learn.microsoft.com/azure/developer/azure-developer-cli/overview[the Azure Developer CLI (azd)] to quickly run this application on Azure Spring Apps. The Azure Developer CLI is an open-source tool that accelerates the time it takes for you to get your application from your local development environment to Azure.

For how to run it with azd, you can refer to https://learn.microsoft.com/azure/spring-apps/quickstart[Deploy your first application to Azure Spring Apps]

== See also

Additional information about using Spring with Azure is available here:

* https://learn.microsoft.com/azure/developer/java/spring/[Spring on Azure]
* https://learn.microsoft.com/azure/developer/java/spring-framework/[Spring Cloud Azure]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]
